name: 'Zigbee Smoke Detector by Gabriel'
packageKey: 'zigbee-smoke-detector by Gabriel'
permissions:
  zigbee: {}
description: "SmartThings driver for Zigbee smoke detector devices"
vendorSupportInformation: "https://support.smartthings.com"
